version: "3.9"
    
services:
  db:
    image: mysql:8.0.25
    ports:
        - "3306:3306"
    volumes:
      - scanit_mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'scanit@123-dev'
      MYSQL_DATABASE: scanit-db
      MYSQL_USER: scanit
      MYSQL_PASSWORD: 'scanit@123-dev'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  scanit_mysql_data: {}